---
title: Among youths tested positive for Covid, higher risk in those hospitalized than those discharged home?
author: 'Jinghong Zeng'
date: '2022-01-18'
---

A recent prospective cohort study on the proportion of youths infected by Covid to have severe outcomes suggests that youths who tested positive for Covid and were hospitalized is more likely to have severe outcomes than those who tested positive for Covid but were discharged home. 

This study only did association analysis, not causal analysis. This apparent difference may be because youths who are in better conditions after getting infected are more likely to get discharged home, otherwise they would be hospitalized. So hospitalization can be associated with many other risk factors such as age and previous medical condition and itself can be a potential confounder. It would be interesting to further analyze the risk difference between the two groups after adjusting for this and other risk factors.

### Reference

Funk AL, Florin TA, Kuppermann N, et al. Outcomes of SARS-CoV-2–Positive Youths Tested in Emergency Departments: The Global PERN–COVID-19 Study. JAMA Netw Open. 2022;5(1):e2142322. https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2787931

